#!/bin/bash
# Tim H 2021  
# Sets a static IP for a virtual machine's ethernet adapter in CentOS 7
# Verified working 8/2/2021 for my CentOS Std Image
# TODO: add support for more DNS servers than just 3

NETWORK_ADAPTER_NAME="ens192"
STATIC_IP="10.0.1.22"

# bomb out if any errors occur
set -e

if [ ! "$USER" == "root" ]; then
    echo "This script must be run as root, aborting."
    exit 2
fi

cat << EOF > /etc/sysconfig/network-scripts/ifcfg-$NETWORK_ADAPTER_NAME

# generated by centos7-static-ip.sh script from Tim H
TYPE="Ethernet"
DEVICE="$NETWORK_ADAPTER_NAME"
NAME="$NETWORK_ADAPTER_NAME"
BOOTPROTO=none
ONBOOT=yes
PREFIX=24
IPADDR=$STATIC_IP
GATEWAY=10.0.1.1
DNS1=10.0.1.11
DNS2=208.67.222.222
DNS3=208.67.220.220
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
IPV6_ADDR_GEN_MODE="stable-privacy"

PROXY_METHOD="none"
BROWSER_ONLY="no"
#UUID="a5382541-64b8-401a-91c4-d9cda91747ab"

EOF

echo "rebooting to apply changes..."
reboot now
