---
- name: Linux (?) CentOS Virtual Machines? Need to use commands that are
    OS independent if possible
  hosts: virtual_machines
  become: yes
  become_method: sudo
  serial: 20
  vars:
    ansible_become_password: password

  tasks:
    - name: VMware Tools installed on Linux
      yum:
        name: open-vm-tools
        state: present

    - name: VMware tools service running and auto-start
      service:
        name: vmtoolsd
        state: started
        enabled: yes
