---
# taken from : https://gist.github.com/kgriffs/8e058d78474836102cd84bf2051c4d68
- name: Update CentOS kernel and reboot
  hosts: linux_centos7
  become: yes
  become_method: sudo
  serial: 20
  vars:
    ansible_become_password: password

  tasks:
    - name: Add ELRepo
      yum:
        name: https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
        state: latest
    - name: Install latest mainline kernel
      yum:
        name: kernel-ml
        state: latest
        enablerepo: elrepo-kernel
    - name: Remake grub config to pick up new kernel
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
    - name: Restart server to ensure configuration changes take hold
      shell: 'sleep 2 && shutdown -r now "Reboot by Ansible" && sleep 5'
      async: 1
      poll: 0
      become: true
# - name: Wait for the server to restart
#  local_action:
#    module: wait_for
#      host={{ inventory_hostname }}
#      port=22
#      delay=60
#  become: false
