---
- name: Basic ubuntu bootstrap
  hosts: debian_family
  become: yes
  become_method: sudo
  vars:
    ansible_become_password: password
    new_host_timezone: "America/New_York"

  tasks:

    - name: remove cdrom repo from apt sources
      lineinfile:
        path: /etc/apt/sources.list
        regexp: 'cdrom'
        line: ''

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Install standard Ubuntu packages
      apt:
        name: apt-file,apt-transport-https,arping,autoconf,automake,
          ca-certificates,curl,dnsutils,gcc,gnupg-agent,gnupg,grep,
          libtool,lsof,make,mlocate,net-tools,netcat,nmap,npm,
          ntpdate,openssh-server,openssl,python3-pip,sed,screen,
          software-properties-common,sysstat,tar,tcpdump,
          tcpflow,telnet,traceroute,unzip,vim,wget
        state: present

    - name: Setup and start VMware tools
      apt:
        name: open-vm-tools
        state: present

    - name: Install Automatic updates
      apt:
        name: unattended-upgrades
        state: present

    - name: Start VMware tools
      service:
        name: open-vm-tools
        state: started
        enabled: yes

    - name: Start automatic updates
      service:
        name: unattended-upgrades
        state: started
        enabled: yes

    - name: set the time zone
      timezone:
        name: "{{ new_host_timezone }}"

    - name: Install NTP client
      apt:
        name: ntp
        state: present

    - name: Ensure NTP is started, will autostart
      service:
        name: ntp
        state: started
        enabled: yes

    - name: Install NodeJS package jsonlint globally.
      npm:
        name: jsonlint
        global: yes

    - name: Install NodeJS package swagger-codegen globally.
      npm:
        name: swagger-codegen
        global: yes

    - name: Install NodeJS package swagger-cli globally.
      npm:
        name: swagger-cli
        global: yes
